mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('taskmanager.urls')),
]

taskmanager/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from taskmanager import views
from taskmanager.forms import LoginForm

app_name = 'taskmanager'

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^task/(?P<task_id>[0-9]+)/$', views.task, name='task'),
    url(r'^user/(?P<user_name>[a-zA-Z0-9]+)/$', views.user, name='user'),
    url(r'^users/$', views.users, name='users'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^addtask', views.addTask, name='addtask'),
    url(r'^deletetask/(?P<task_id>[0-9]+)/$', views.deleteTask, name='deletetask'),
    url(r'^register', views.register, name='register'),
    url(r'^group/(?P<group_id>[0-9]+)/$', views.group, name='group'),
    url(r'^addgroup/$', views.addgroup, name='addgroup'),
    url(r'^addMeToGroup/(?P<group_id>[0-9]+)/$$', views.addMeToGroup, name='addmetogroup'),
    url(r'^addTaskToGroup/(?P<group_id>[0-9]+)/$', views.addTaskToGroup, name='addtasktogroup'),
    url(r'^done/(?P<task_id>[0-9]+)/$', views.done, name='done'),
    url(r'^search/$', views.search, name='search'),
    url(r'^withdraw/(?P<group_id>[0-9]+)/$', views.withdrawFromGroup, name='withdraw'),
    url(r'^edittask/(?P<task_id>[0-9]+)/$', views.editTask, name='edittask'),
    url(r'^makeadmin/(?P<user_name>[a-zA-Z0-9]+)/$', views.makeAdmin, name='makeadmin'),
    url(r'^deleteuser/(?P<user_name>[a-zA-Z0-9]+)/$', views.deleteUser, name='deleteuser'),
    url(r'^deleteTokens/$', views.deleteTokens, name='deletetokens')



]

taskmanager/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class GroupNames(models.Model):
    name = models.CharField(max_length=32, blank=True, null=True)
    id = models.AutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'group_names'


class Role(models.Model):
    role_name = models.CharField(primary_key=True, max_length=32)

    class Meta:
        managed = False
        db_table = 'role'


class Task(models.Model):
    title = models.CharField(max_length=32, blank=True, null=True)
    description = models.CharField(max_length=160, blank=True, null=True)
    id = models.AutoField(primary_key=True)
    deadline = models.DateTimeField(blank=True, null=True)
    label = models.CharField(max_length=32, blank=True, null=True)
    done = models.BooleanField(default=False, db_column='done')
    class Meta:
        managed = False
        db_table = 'task'


class Token(models.Model):
    access_token = models.CharField(max_length=32, blank=True, null=True)
    expiration_date = models.DateTimeField(blank=True, null=True)
    token_id = models.AutoField(db_column='token_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'token'


class User(models.Model):
    name = models.CharField(primary_key=True, max_length=32)
    password = models.CharField(max_length=32, blank=True, null=True)
    email = models.CharField(max_length=32, blank=True, null=True)
    role_role_name = models.ForeignKey(Role, models.DO_NOTHING, db_column='role_role_name')
    token_token = models.ForeignKey(Token, models.DO_NOTHING, db_column='token_token_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'user'


class UserGroup(models.Model):
    user_name = models.ForeignKey(User, models.DO_NOTHING, db_column='user_name')
    group_names = models.ForeignKey(GroupNames, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'user_group'
        unique_together = (('user_name', 'group_names'),)


class GroupTask(models.Model):
    group_id = models.ForeignKey(GroupNames, models.DO_NOTHING, db_column='group_id')
    task_id = models.ForeignKey(Task, db_column='task_id', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'group_task'
        unique_together = (('group_id', 'task_id'),)


class UserTask(models.Model):
    user_name = models.ForeignKey(User, models.DO_NOTHING, db_column='user_name')
    task = models.ForeignKey(Task, db_column='task_id', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'user_task'
        unique_together = (('user_name', 'task'),)

taskmanager/forms.py
import datetime
from audioop import reverse

from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Button
from django import forms
from django.forms import PasswordInput
from crispy_forms.helper import FormHelper

from taskmanager import views


class LoginForm(forms.Form):
    login = forms.CharField(label='Login', max_length=32)
    password = forms.CharField(label='Password', max_length=100, widget=PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('log in', 'Sign In'))


class RegisterForm(forms.Form):
    login = forms.CharField(label='Login', max_length=32)
    email = forms.EmailField(required=True)
    password = forms.CharField(label='Password', max_length=100, widget=PasswordInput())
    repeatPassword = forms.CharField(label='Repeat password', max_length=100, widget=PasswordInput(), required=True)

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('register', 'Register'))


class TaskForm(forms.Form):
    title = forms.CharField(label='Title', max_length=32)
    description = forms.CharField(label='Description', max_length=160)
    deadline = forms.DateField(label='Deadline', initial=datetime.date.today)
    label = forms.CharField(label='Label', max_length=32)

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

class AddGroupForm(forms.Form):
    name = forms.CharField(label='Group name', max_length=32)

    def __init__(self, *args, **kwargs):
        super(AddGroupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('addgroup', 'Add group'))

taskmanager/views.py
from django.db import IntegrityError, connection
from django.db import InternalError
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from taskmanager.auth import TOKEN, createToken, getCurrentUser, authentication, hashPassword, set_cookie, \
    adminAuthentication
from taskmanager.forms import LoginForm, TaskForm, RegisterForm, AddGroupForm
from taskmanager.models import User, Task, Token, UserTask, GroupNames, UserGroup, GroupTask, Role


@adminAuthentication
def users(request):
    user = getCurrentUser(request)
    role = Role.objects.get(user__name=user.name)
    roleName = role.role_name
    if roleName == 'admin':
        users = User.objects.all()
        return render(request, 'taskmanager/users.html', {'users': users})
    else:
        return HttpResponse(404)


@authentication
def task(request, task_id):
    user = getCurrentUser(request)
    try:
        task = get_object_or_404(Task.objects.filter(id=task_id))
        isOwnerByTask = Task.objects.filter(Q(id=task_id, usertask__user_name__name=user.name)).count() > 0
        try:
            group = GroupNames.objects.get(grouptask__task_id__id=task_id)
            isOwnerByGroup = User.objects.filter(name=user.name, usergroup__group_names_id=group.id).count() > 0
        except GroupNames.DoesNotExist:
            isOwnerByGroup = False
        return render(request, 'taskmanager/task.html', {'task': task, 'isowner': isOwnerByTask or isOwnerByGroup})
    except Task.DoesNotExist:
        return HttpResponse(status=404)


@authentication
def user(request, user_name):
    try:
        user = User.objects.get(name=user_name)
        query = 'SELECT task.title, task.id,task.deadline,task.label,task.description FROM task LEFT JOIN group_task on task.id = group_task.task_id LEFT JOIN group_names on group_task.group_id = group_names.id LEFT JOIN user_group on group_names.id = user_group.group_names_id left join user_task on user_task.task_id = task.id WHERE user_group.user_name = "' + user_name + '" or user_task.user_name = "' + user_name + '" order by task.done,task.deadline'
        tasksList = list(Task.objects.raw(raw_query=query))
        groupList = GroupNames.objects.filter(usergroup__user_name=user_name)
        return render(request, 'taskmanager/user.html',
                      {'tasks': tasksList, 'user': user, 'groups': groupList, 'error': False})
    except Task.DoesNotExist:
        return render(request, 'taskmanager/user.html', {'error': True})


def login(request):
    problem = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            formLogin = form.cleaned_data['login']
            formPassword = form.cleaned_data['password']
            try:
                formUser = User.objects.get(pk=formLogin)
                hashedPassword = hashPassword(formPassword)
                if formUser.password == hashedPassword:
                    token = request.COOKIES.get(TOKEN)
                    if token == '':
                        tokenObject = createToken()
                    else:
                        try:
                            tokenObject = Token.objects.get(access_token=token)
                            if tokenObject.expiration_date < timezone.now():
                                tokenObject = createToken()
                        except Token.DoesNotExist:
                            tokenObject = createToken()
                    formUser.token_token_id = tokenObject.pk
                    formUser.save()
                    print(formUser.name)
                    response = HttpResponseRedirect(reverse('taskmanager:user', kwargs={'user_name': formUser.name}))
                    set_cookie(response, TOKEN, tokenObject.access_token)
                    return response
                else:
                    problem = 'Wrong password or login'
            except User.DoesNotExist:
                problem = 'Wrong login or password'
    response = render(request, 'taskmanager/login.html',
                      {'problem': problem, 'loginForm': LoginForm()})
    response.delete_cookie(TOKEN)
    return response


def logout(request):
    res = HttpResponseRedirect(reverse('taskmanager:login'))
    res.delete_cookie(TOKEN)
    return res


@authentication
def addTask(request):
    message = error = None
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            deadline = form.cleaned_data['deadline']
            label = form.cleaned_data['label']
            newTask = Task(title=title, description=description, deadline=deadline, label=label)
            newTask.save(force_insert=True)
            user = getCurrentUser(request)
            UserTask.objects.create(user_name=user, task_id=newTask.pk)
            message = 'Success'
        error = form.errors
    return render(request, 'taskmanager/addtask.html', {'form': TaskForm(), 'error': error, 'message': message})


@authentication
def deleteTask(request, task_id):
    user = getCurrentUser(request)
    try:
        Task.objects.get(id=task_id).delete()
        return HttpResponseRedirect(reverse('taskmanager:user', kwargs={'user_name': user.name}))
    except Task.DoesNotExist:
        return render(request, 'taskmanager/task.html', {'task_id': task_id, })


def register(request):
    problem = None
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            userName = form.cleaned_data['login']
            password = form.cleaned_data['password']
            repass = form.cleaned_data['repeatPassword']
            email = form.cleaned_data['email']
            if password == repass:
                token = createToken()
                newUser = User(name=userName, password=hashPassword(password), email=email, role_role_name_id='user',
                               token_token_id=token.pk)
                try:
                    newUser.save(force_insert=True)
                except IntegrityError:
                    problem = 'User with this login already exists'
                except InternalError:
                    problem = 'Login cant use polish diacritic signs'
            else:
                problem = 'Passwords are not equal'
        else:
            problem = form.errors
    return render(request, 'taskmanager/register.html', {'registerForm': RegisterForm(), 'problem': problem})


@authentication
def group(request, group_id):
    groupObj = GroupNames.objects.get(id=group_id)
    groupUsers = User.objects.filter(usergroup__group_names_id=group_id)
    user = getCurrentUser(request)
    isMember = GroupNames.objects.filter(usergroup__user_name=user.name, id=group_id).count() > 0
    tasksList = Task.objects.filter(grouptask__group_id=group_id).order_by('done', 'deadline')
    return render(request, 'taskmanager/group.html',
                  {'group': groupObj, 'users': groupUsers, 'tasks': tasksList, 'isMember': isMember})


@authentication
def addgroup(request):
    user = getCurrentUser(request)
    problem = None
    message = None
    if request.method == 'POST':
        form = AddGroupForm(request.POST)
        if form.is_valid():
            groupName = form.cleaned_data['name']
            group = GroupNames(name=groupName)
            group.save()
            UserGroup.objects.create(group_names_id=group.pk, user_name=user)
            message = "Success"
            return HttpResponseRedirect(reverse('taskmanager:user', kwargs={'user_name': user.name}))
        else:
            problem = form.errors
    return render(request, 'taskmanager/addgroup.html', {'form': AddGroupForm(), 'problem': problem})


@authentication
def addMeToGroup(request, group_id):
    user = getCurrentUser(request)
    newUserGroup = UserGroup(user_name_id=user.name, group_names_id=group_id)
    newUserGroup.save()
    return HttpResponseRedirect(reverse('taskmanager:group', kwargs={'group_id': group_id}))


@authentication
def addTaskToGroup(request, group_id):
    message = error = None
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            deadline = form.cleaned_data['deadline']
            label = form.cleaned_data['label']
            newTask = Task(title=title, description=description, deadline=deadline, label=label)
            newTask.save(force_insert=True)
            newGroupTask = GroupTask(group_id_id=group_id, task_id_id=newTask.pk)
            newGroupTask.save()
            message = 'Success'
            return HttpResponseRedirect(reverse('taskmanager:group', kwargs={'group_id': group_id}))
        error = form.errors
    return render(request, 'taskmanager/addtask.html', {'form': TaskForm(), 'error': error, 'message': message})


@authentication
def main(request):
    user = getCurrentUser(request)
    return HttpResponseRedirect(reverse('taskmanager:user', kwargs={'user_name': user.name}))


@authentication
def done(request, task_id):
    taskObj = Task.objects.get(id=task_id)
    taskObj.done = True
    taskObj.save()
    return HttpResponseRedirect(reverse('taskmanager:main'))


@authentication
def search(request):
    users = None
    groups = None
    tasks = None
    query = None
    if request.method == 'GET':
        query = request.GET['query']
        searchQuery = '\S*' + query + '\S*'
        users = User.objects.filter(name__regex=searchQuery)
        tasks = Task.objects.filter(Q(title__regex=searchQuery) | Q(label__regex=searchQuery))
        groups = GroupNames.objects.filter(name__regex=searchQuery)

taskmanager/templates/taskmanager/addgroup.html
{% extends 'taskmanager/base.html' %}
{% load crispy_forms_tags %}
{% crispy addgroup_form addgroup_form.helper %}
{% block content %}
    {%  if error %}
    <div class="alert alert-danger">
      <strong> {{ error }}</strong>
    </div>
    {%  elif message %}
    <div class="alert alert-success">
      <strong>Success!</strong> {{ message }}
    </div>
    {%  endif %}
    {% crispy form %}
    <a href={% url 'taskmanager:main' %}>
        <button class="btn btn-default">Back</button>
    </a>
{% endblock content %}

taskmanager/templates/taskmanager/addtask.html
{% extends 'taskmanager/base.html' %}

{% load crispy_forms_tags %}
{% crispy addtask_form addtask_form.helper %}
{% block content %}
    {%  if error %}
    <div class="alert alert-danger">
      <strong> {{ error }}</strong>
    </div>
    {%  elif message %}
    <div class="alert alert-success">
      <strong>Success!</strong> {{ message }}
    </div>
    {%  endif %}
    {% crispy form %}
    <a href="{% url 'taskmanager:main' %}">
    <button type="button" class="btn btn-default">Back</button>
    </a>
{% endblock content %}

taskmanager/templates/taskmanager/base.html
{% load static %}
<html>
<head>
    <title>TaskManager</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="page-header">
    <div class="row">
        <div class="col-sm-6 pull-right">
            <form action="{% url 'taskmanager:search' %}">
                <div class="input-group stylish-input-group">
                    <input type="text" class="form-control" name="query" placeholder="Search">
                    <span class="input-group-addon">
                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>

        <div class="col-1">
            <h1><a href="{% url 'taskmanager:main' %}">TaskManager</a></h1>
        </div>
    </div>

</div>
<div class="content container" style="float: none;">
    <div style="float: none">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>
<script>
    function goBack() {
        window.history.back();
        location.reload();
    }
</script>

taskmanager/templates/taskmanager/edittask.html
{% extends 'taskmanager/base.html' %}

{% load crispy_forms_tags %}
{% crispy addtask_form addtask_form.helper %}
{% block content %}
    {%  if error %}
    <div class="alert alert-danger">
      <strong> {{ error }}</strong>
    </div>
    {%  elif message %}
    <div class="alert alert-success">
      <strong>Success!</strong> {{ message }}
    </div>
    {%  endif %}
    {% crispy form %}
    <a href="{% url 'taskmanager:main' %}">
    <button type="button" class="btn btn-default">Back</button>
    </a>
{% endblock content %}

taskmanager/templates/taskmanager/group.html
{% extends 'taskmanager/base.html' %}
{% block content %}
    <a href="{% url 'taskmanager:withdraw' group.id %}">
        <button type="submit" class="btn btn-danger toRight">Withdraw</button>
    </a>
    {% if isMember %}
        <a href="{% url 'taskmanager:addtasktogroup' group.id %}">
            <button type="submit" class="btn btn-default toRight">Add task to this group</button>
        </a>
    {% else %}
        <a href="{% url 'taskmanager:addmetogroup' group.id %}">
            <button type="submit" class="btn btn-default toRight">Add me to this group</button>
        </a>
    {% endif %}
    <h1>Group: {{ group.name }}</h1>

    {% if tasks|length == 0 %}
        <p>No task in this group!</p>
    {% else %}
        <div class="list-group">
            {% for task in tasks %}
                <a href="{% url 'taskmanager:task' task.id %}"
                   class="list-group-item list-group-item-action {% if task.done %}done{% endif %}">{{ task.title }}<div class="toRight">deadline: {{ task.deadline }}</div></a>
            {% endfor %}
        </div>
    {% endif %}
    <h1>Users:</h1>
    <div class="list-group">
        {% for user in users %}
            <a href="{% url 'taskmanager:user' user.name %}"
               class="list-group-item list-group-item-action">{{ user.name }}</a>
        {% endfor %}
    </div>
    <div>
        <a onclick="goBack()">
            <button type="button" class="btn btn-primary">Back</button>
        </a>
    </div>
{% endblock content %}

taskmanager/templates/taskmanager/login.html
{% extends 'taskmanager/base.html' %}
{% load crispy_forms_tags %}
{% crispy login_form login_form.helper %}
{% block content %}
    <a href="{% url 'taskmanager:register' %}">
    <button type="button" class="btn btn-warning toRight">Sign up</button>
    </a>
    <h1 style="text-align: center">Sign in</h1>
    {% if problem %}
        <div class="alert alert-warning">Authorization failed!</div>
    {% endif %}
    {% crispy loginForm %}
{% endblock content %}

taskmanager/templates/taskmanager/register.html
{% extends 'taskmanager/base.html' %}
{% load crispy_forms_tags %}
{% crispy login_form login_form.helper %}
{% block content %}
    <a href="{% url 'taskmanager:login' %}">
        <button type="submit" class="btn btn-danger toRight">Cancel</button>
    </a>
    <h1 style="text-align: center">Sign up</h1>
    {% if problem %}
        <div class="alert alert-warning">{{ problem }}</div>
    {% endif %}
    {% crispy registerForm %}

{% endblock content %}

taskmanager/templates/taskmanager/search.html
{% extends 'taskmanager/base.html' %}
{% block content %}
    <h1>Search results:</h1>
    {% if tasks|length == 0 and groups|length == 0 and users|length == 0 %}
        No results for query <strong>{{ query }} </strong>
    {% endif %}
    {% if tasks|length > 0 %}
        <h3>Tasks:</h3>
        <div class="list-group">
            {% for task in tasks %}
                <a href="{% url 'taskmanager:task' task.id %}"
                   class="list-group-item list-group-item-action {% if task.done %}done{% endif %}">{{ task.title }}</a>
            {% endfor %}
        </div>
    {% endif %}
    {% if groups|length > 0 %}
        <h3> Groups:</h3>
        <div class="list-group">
            {% for group in groups %}
                <a href="{% url 'taskmanager:group' group.id %}"
                   class="list-group-item list-group-item-action">{{ group.name }}</a>
            {% endfor %}
        </div>
    {% endif %}
    {% if users|length > 0 %}
        <h3> Users:</h3>
        <div class="list-group">
            {% for user in users %}
                <a href="{% url 'taskmanager:user' user.name %}"
                   class="list-group-item list-group-item-action">{{ user.name }}</a>
            {% endfor %}
        </div>
    {% endif %}

    <div>
        <a href="{% url 'taskmanager:main' %}">
            <button type="button" class="btn btn-primary">Back</button>
        </a>
    </div>
{% endblock %}

taskmanager/templates/taskmanager/task.html
{% extends 'taskmanager/base.html' %}
{% block content %}
{% if isowner %}
    <a href={% url 'taskmanager:deletetask' task.id %}>
        <button type="button" class="btn btn-danger toRight">Delete</button>
    </a>

    <a href={% url 'taskmanager:done' task.id %}>
        <button type="button" class="btn btn-success toRight">Done</button>
    </a>

    <a href={% url 'taskmanager:edittask' task.id %}>
        <button type="button" class="btn btn-warning toRight">Edit</button>
    </a>
{% endif %}

    <h2> {{ task.title }}</h2>
    <ul>
        <li>description: <strong>{{ task.description }}</strong></li>
        <li>label: <strong>{{ task.label }}</strong></li>
        <li>deadline: <strong>{{ task.deadline }}</strong></li>
        <li> {% if task.done %} <p class="bg-success"> status: Done</p> {% else %} <p class="bg-danger"> status: Waiting</p> {% endif %}</li>
    </ul>
    <div>
            <a  href="{% url 'taskmanager:main' %}" >
                <button type="button" class="btn btn-primary">Back</button>
            </a>
    </div>
{% endblock content %}

taskmanager/templates/taskmanager/user.html
{% extends 'taskmanager/base.html' %}

{% block content %}

    <a href={% url 'taskmanager:logout' %}>
        <button type="button" class="btn btn-primary toRight">Logout ({{ user.name }})</button>
    </a>
    {% if user.role_role_name.role_name == 'admin' %}
        <a href="{% url 'taskmanager:users' %}">
        <button type="button" class="btn btn-default toRight">
          <span class="glyphicon glyphicon-cog"></span> Admin Panel
        </button>
        </a>
    {% endif %}
    <h1>{{ user.name }}</h1>
    <p>Email: {{ user.email }}</p>
    <div class="row form-group">
    <div  class="col-1">
        <h1>Tasks:</h1>
    </div>
        <a href="{% url 'taskmanager:addtask' %}" class="col-12">
            <button type="button" class="btn btn-default toRight">Add</button>
        </a>
    </div>
    {% if error %}
        <div class="alert alert-warning">Something went wrong</div>
    {% endif %}
    {% if tasks|length == 0 %}
        <p>No tasks for you!</p>
    {% else %}
        <div class="list-group">
            {% for task in tasks %}
                <a href="{% url 'taskmanager:task' task.id %}"
                   class="list-group-item list-group-item-action {% if task.done %}done{% endif %}">{{ task.title }}<div class="toRight">deadline: {{ task.deadline }}</div></a>
            {% endfor %}
        </div>
    {% endif %}

    <div class="row form-group">
    <div  class="col-1">
        <h1>Groups:</h1>
    </div>
        <a href="{% url 'taskmanager:addgroup' %}" class="col-12">
            <button type="button" class="btn btn-default toRight">Add</button>
        </a>
    </div>
    {% if groups|length == 0 %}
        <p>You dont belong to any group</p>
    {% else %}
        <div class="list-group">
            {% for group in groups %}
                <a href="{% url 'taskmanager:group' group.id %}"
                   class="list-group-item list-group-item-action">{{ group.name }}</a>
            {% endfor %}
        </div>
    {% endif %}

{% endblock content %}

taskmanager/templates/taskmanager/users.html
{% extends 'taskmanager/base.html' %}
{% block content %}
    <a href="{% url 'taskmanager:deletetokens' %}"  class="btn-group toRight">
        <button type="button" class="btn btn-warning ">Delete Tokens</button>
    </a>

    <div>
            <a  href="{% url 'taskmanager:main' %}" >
                <button type="button" class="btn btn-primary">Back</button>
            </a>
    </div>
    <h1>Users:</h1>
    <div class="list-group">
        {% for user in users %}
           <a href="{% url 'taskmanager:user' user.name %}"
              class="list-group-item list-group-item-action
                {% if user.role_role_name.role_name == 'admin' %}
                    green
                {%  endif %}

                ">

                    {{ user.name }}
                       {% if user.role_role_name.role_name == 'admin' %}
                            (admin)
                        {%  endif %}
            </a>
                <div style="margin: 10px">
                    {% if user.role_role_name.role_name != 'admin' %}
                    <a href="{% url 'taskmanager:makeadmin' user.name %}"  class="btn-group">
                        <button type="button" class="btn btn-success toRight">Make admin</button>
                    </a>
                    {% endif %}

                    <a href="{% url 'taskmanager:deleteuser' user.name %}"  class="btn-group">
                        <button type="button" class="btn btn-danger toRight">Delete user</button>
                    </a>
                </div>
        {% endfor %}

    </div >
{% endblock content %}